IF DB_ID('EmployeeDB') IS NULL CREATE DATABASE EmployeeDB;
GO
USE EmployeeDB;
GO
IF OBJECT_ID('employees','U') IS NULL BEGIN
CREATE TABLE employees(id BIGINT IDENTITY(1,1) PRIMARY KEY,name VARCHAR(100) NOT NULL,email VARCHAR(150) NOT NULL UNIQUE,department VARCHAR(100) NOT NULL,designation VARCHAR(100) NOT NULL);
END
GO
